### ISSUE TITLE
Remove dependency on Spring for non-Spring uses

### ISSUE THREAD

**Issue by tomwhoiscontrary** [MariaDB4j/MariaDB4j#698]
I am not using Spring. If i depend on MariaDB4j, i get a transitive dependency on Spring Core. I would prefer it if this were not the case; of course, it is always preferable to minimise dependencies, and some of my colleagues would get quite flustered if they saw a Spring JAR appearing on their classpath.

As far as i can tell, the only use of Spring for non-Spring use cases is in [Util:: extractFromClasspathToFile](https://github.com/vorburger/MariaDB4j/blob/main/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Util.java#L116), where a `PathMatchingResourcePatternResolver` is used to locate the native database files as classpath resources.

Would it be possible to do this without using Spring?

It seems like it might not be too hard just using basic JDK features. You have the package path - something like "ch/vorburger/mariadb4j/mariadb-10.2.11/win32". You could add on "bin/mysql" (or "bin/mysql.exe" - try both) to make a path to a file that should exist, then do `Class::getResource` to find a URL to that. Once you've found it, you can construct a URL to the directory or JAR file it's inside, and then enumerate the files in that.

This would work as long as the database files are on the classpath as a straightforward directory or JAR resource. If they have been added in some more sophisticated way, this will not work, whereas the Spring approach presumably would.

Accordingly, it might be desirable to have some sort of fallback, where if Spring Core is available, `PathMatchingResourcePatternResolver` is used, and if not, a JDK-only approach is used.

Is this at all appealing?

**Comment by vorburger** [comment]
I would be open to reviewing a Pull Request which rewrites that without
using Spring.

Perhaps it's something that could be worked towards in a series of several
PRs? Maybe something like:

A. Make finding DB binaries pluggable; either from class path, or fixed
file path? (That's already supported, see the related test.)

B. Make the strategy by which extraction from resources on the classpath
itself happen pluggable. There would be (at least) 2, the 1. of them as-is
(and this would perhaps best be moved into the existing
MariaDB4j-springboot module), then 2. another "pure JDK" one, as outlined
above, but 3. potentially also a NOOP one (if fixed local file path to DB
is used ; unless the code is changed so that no such strategy
implementation is required at all). And 4. leave the door open for others,
if someone has any special classpath requirements (e.g. for someone who
fancies plugging in e.g. a.... ClassGraph-based Impl?)

The end user API shouldn't change at all, ideally. If one has existing
code, it should always just still work as-is.

**Comment by vorburger** [comment]
@tomwhoiscontrary do you still have any interest to contribute a Pull Request for this? Otherwise I would like to close this.

**Comment by tomwhoiscontrary** [comment]
I think realistically i won't have time to work on this, sadly.
